"""creating m2m relationship between tags and ledger

Revision ID: 123a19334ab0
Revises: 103bce3da3cc
Create Date: 2020-12-09 10:07:52.011588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '123a19334ab0'
down_revision = '103bce3da3cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_tag',
    sa.Column('ledger_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ledger_id'], ['ledger.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ledger_tag')
    # ### end Alembic commands ###
